osx_image: xcode11.5
sudo: required
dist: trusty
language: node_js
node_js:
  - 12
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
before_install:
  - npm install -g xvfb-maybe
  - npm install -g node-gyp
install:
  - npm i
script:
  - npm run build
branches:
  only:
    - master
