matrix:
  include:
    - os: linux
      language: node_js
      node_js: "11.15"
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "11.15"
    - os: windows
      language: node_js
      node_js: "11.15"
script:
  - |
    export PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm install;
      npm run build && ls -la build;
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      npm install;
      npm run build && ls -la build;
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm install;
      npm run build && ls -la build;
    fi
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    #- 'build/nim-pools-hub-miner_$PACKAGE_VERSION_amd64.snap'
    - "build/NIM Pools Hub Miner-$PACKAGE_VERSION.AppImage"
    - "build/NIM Pools Hub Miner-$PACKAGE_VERSION-mac.zip"
    - "build/NIM Pools Hub Miner-$PACKAGE_VERSION.dmg"
    - "build/NIM Pools Hub Miner-$PACKAGE_VERSION.dmg.blockmap"
    - "build/NIM Pools Hub Miner Setup $PACKAGE_VERSION.exe"
    - "build/NIM Pools Hub Miner Setup $PACKAGE_VERSION.exe.blockmap"
  skip_cleanup: "true"
  on:
    tags: true
