version: 0.0.{build}

skip_non_tags: true

branches:
  only:
    - master
    - /v\d*\.\d*\.\d*/

image:
  - Visual Studio 2017
  - Ubuntu
  - macOS

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node 12 x64
  - sh: nvm install 12
  - git reset --hard HEAD
  - npm i
  - node --version

build_script:
  - npm run release

test: off
