version: 0.1.{build}

skip_non_tags: true

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node 14 x64
  - cmd: appveyor DownloadFile http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_451.48_win10.exe -FileName cuda.exe
  - cmd: cuda.exe -s
  - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0\libnvvp;%PATH%
  - cmd: set "CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v11.0"
  - sh: nvm install 12
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install freeglut3 freeglut3-dev libxi-dev libxmu-dev
  - sh: sudo apt-get install gcc-6 g++-6 linux-headers-$(uname -r) nvidia-384 -y
  - sh: wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_450.51.05_linux.run
  - sh: sudo sh cuda_11.0.2_450.51.05_linux.run --silent --toolkit --override
  - sh: export CUDA_PATH=/usr/local/cuda-11.0
  - sh: export PATH="$PATH:/usr/local/cuda-11.0/bin"
  - sh: export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64\
      ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - git reset --hard HEAD
  - npm i
  - node --version

build_script:
  - npm run release

test: off
