version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2017
  - Ubuntu
  - macOS

platform:
  - x64

environment:
  nodejs_version: "12.18.0"

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - git reset --hard HEAD
  - npm i
  - node --version

build_script:
  - yarn build

test: off
